function newStruct = newRenderStruct
%Initialize new renderstruct
newStruct=struct('volString','','brain_at',[],'dim',[],'mat',[],'opacity',1.0, ...
    'regionvalues',[],'singleColorFlag',0,'singleColor',[236/255 214/255 214/255],'brain_colormap','bone','custom_colormap',[], ...
    'brain_colormapidx',1,'brain_colormaprange',[],'nodes',0,'pipes',0, 'connectivityMatrix',[], ...
    'nodeScale',2.5,'nodeSchema',[],'nodeProps',[],'nodeStyle',1,'pipeScale',1.5, ...
    'pipeScheme',1,'pipeColorHyperCube',[],'pipeCouplet',[rand(1,3);rand(1,3)], ...
    'pipeColorMap','jet','pipeCoupletThreshold',50,'pipeStyle',1,'pipeUniform',0,'renderRes',[], ...
    'currentVol',[],'saveImages',0,'saveMovie',0,'figstr','','mainHandle',[],'numberROI',[]);